config/routes.rb
YeaAmerica::Application.routes.draw do
  get 'next', to: 'next#index', as: 'next'
  get 'location', to: 'location#index', as: 'location'
  get 'about', to: 'about#index', as: 'about'
  get 'speakers', to: 'speakers#index', as: 'speakers'

  resources :photos

  get "home/index"

   root :to => 'home#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
  end
end

app/controllers/next_controller.rb
class NextController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/next_helper.rb
module NextHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/about/index.html.erb
<h1>About Yea America</h1>
<p>Yea America began in 1993 when our grandmother, Dianne McCrea, wanted her grandchildren to understand what it meant to have the freedom in America we have and what the troops in uniform did for our country. She ensured that all of her grandchildren would go through life understanding the cost it took for us to be free.</p>

app/views/home/index.html.erb
<h1>Yea America!</h1>
<section class="norm">
	Yea America celebrates 3 important and pertinent things that protect us in life...God, the troops and family. 
<ol>
	<li><strong>God</strong> is The Protector and does not need a formal introduction as He defines it in His being...see Jesus and the Holy Spirit as well.</li>
	<li>The <strong>troops</strong> protect our country from tyranny and oppression. They protect the rights of the people and create order in a world with a plethora of chaos.</li>
	<li>The <strong>family</strong> protects the children and wife to be raised in a safe environment that points to Christ. Train up a child in the way he should go; even when he is old he will not depart from it. (Proverbs 22:6)</li>
</ol>
	  All 3 would sacrifice their lives for others. The ultimate sacrifice has already been paid (1 Timothy 1:15) and He teaches both countries and families where life, liberty and the pursuit of happiness are truly found. If you do not have something to celebrate this day, celebrate the fact that Someone died so that you could live. I think that is a lot to consider.
</section>
<section style="text-align:center;">
	<%= image_tag "american-soldier-with-gun.jpg", alt: "American-Soldier-with-Gun" %>
</section>
<br />
<br />
<br />
<br />
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yea America</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lusitana' rel='stylesheet' type='text/css'>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
</head>
<body>
  <header id="header" class="">
      <%= render "shared/menu" %>
  </header><!-- /header -->
  <section class="headerright">
    
  </section><!-- /headerright -->
  <section class="footerleft">
    
  </section>
    <footer>
      Yea America 2014 &copy;
    </footer>
  <section id="body">  
  	<section id="core_content">
  		<%= yield %>
  	</section>
  </section>
    
  

  <script type="text/javascript">
$( ".menuitems a" ).hover(function() {
  $(this).fadeIn( 100 );
});
</script>
</body>

</html>

app/views/location/index.html.erb
<h1>Location</h1>

<p>Horseshoe Bay, TX</p>
<p>We pile in up to 80 people in a small condominium that one day we believe will slide into the lake because of surpassing the weight the building can withstand. It is located on Lake LBJ.</p>
<section style="text-align: center; padding: 10px;">
<%= image_tag "Condo.jpg", alt: "The Size of the Place" %>
</section>

app/views/next/index.html.erb
<h1>What's Next?</h1>
<p>Ever heard of Columbus?</p>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

<script src="galleria/galleria-1.3.5.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
<div class="galleria">
    <%= image_tag "Bryan.JPG", size: "700x400" %>
   
    <%= image_tag "Mere1.JPG", size: "700x400"  %>
</div>

<script>
    Galleria.loadTheme('galleria/themes/classic/galleria.classic.min.js');
    Galleria.run('.galleria');
</script>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/shared/_menu.html.erb
<menu type="context toolbar" class="menuitems">
	<li><%= link_to 'About', '/about' %></a></li>
	<li><%= link_to 'Photos', photos_path %></li>
	<li><%= link_to 'Speakers', '/speakers' %></li>
	<li><%= link_to 'Location', '/location' %></li>
	<li><%= link_to 'Up Next', '/next' %></li>
</menu>

app/views/speakers/index.html.erb
<h1>Speakers</h1>

<p>World War II Vet</p>
<p>Clint Bruce</p>

<p>Daniel</p>
<p></p>